## Impact and Outcomes


### Insights gained from this collaboration

* One of the more impactfull insights gained was from observing the increase in the amount of students coming from the LA Area. 
    - This means there is an increasing proportion of students who might have a harder time to adjusting to life in Chico than a student from the North State. 
    - Chemistry 111 is seeing this increase more so than the average Chico State student. 
    - This adjustment is on top of learning how to be a chemist! They have to learn how to be successful in a more adaptive way. 
    - This means that all the issues and discussions around campus about how Chico State being a Hispanic Serving institution (Starting Fall 2016), and the difficulties with "belonging syndrome" causing additional stress are going to be more pronounced in Chemistry 111 than in other classes around campus. 
    - Chemistry instructors need to know that their classes may be hit harder with these issues, and that they may have to address it explicitly. 
    
* About 15% of students enrolling in Chemistry 111do not meet the entry level requirements in either Math or English. This could result in an inability to reduce the DFW rate below around 15%, regardless of the redesign. 

* This course redesign was shown to improve the GPA and lower the failure rate for Chemistry 111 after controlling for other student characteristics. 
    - But instructors should be cognizant of the impact a redesign can have on the top performing students. What works for the "D" students doesn't always work with the "A" students. 



### Faculty Impact

* This project will benefit the RTP process for Robin Donatello (at least). The grant writing and presentations will be considered under Professional Growth and Achievement. 

* The information gained as part of this analysis process can be used to inform the larger campus Graduation Initiative 2025 conversation around student learning programs. This would count as service to the University.



### Dissimenation 
This work has been/will be presented in the following venues

* _Implementing a flipped classroom and active learning techniques in general chemistry to augment student success at a mid-sized rural university._ Poster Presentation at the 253 American Chemical Society National Meeting and Exposition, San Francisco, CA, April 2-6, 2017
* _Examining the effect of a pedagogical change in a high failure rate college science course in the face of a shift demographic student body_. Oral Presentation at the Joint Statistical Meetings, Baltimore MD, July 29-August 3, 2017.
* [In Submission] Oral Presentation at the 23rd Annual Center for Excellence in Learning and Teaching Conference, Chico, CA, Oct 5-6th, 2017. 
* We plan on writing a paper for the Journal of Chemistry Education discussing and promoting this type of interdisciplinary collaboration. 

## Creating Community
One of the best outcomes of this project is a strong interdisciplinary connection. Connecting an older, tenured professor in Chemistry with a Junior professor of Statistics benefits both parties, and their respective department and joint college has far reaching benefits. 

* Having an interdisciplinary conversation on a regular (nearly weekly) basis allows the team members to really learn from each other. 
    - Erik learned a little bit about the power (and limitations) of Statistics. 
    - Robin learned more about what goes into each type of learning enhancement and what contributes to student success.
* It was delightful to have a student (from a previous statistics class of mine) stop me in the hallway and say that they saw my work in Erik's Chemistry 112 class regarding the impact of SI in Chem 111. 
    - This is a clear example of students being exposed to the reality that faculty work together across disciplines, and that both Science and Education work best when not existing in a department silo. 
    - Not just for their own research on some chemical or biological outcome, but also with the shared goal of improving course success. 
    - This also demonstrates the importance of sharing information. Not just with other faculty members but with students also. 

## Sustainability on Chico State campus 

* The work done under this Sustaining Success project was used as a pilot study for an Exceptional Service Assigned Time internal grant awarded to Robin Donatello for Spring 18. The aim for that grant is to build a more generalizable framework for assessing the impact of course redesigns or other learning enhancement programs that can be used across campus. 

* Chico State is working towards the GI202 goals, which will undoubtedly include an examination of student learning enhancements such a SI and other course redesigns. The information gained throughout this Sustaining Success project can help to inform the campus Graduation Initiative Team. 


## Advice & Lessons Learned from a Statisticians Perspective
* 80% of the time in any analysis project is spent in data preparation. Plan accordingly. 
* Request security clearance and access to the databases directly, *or* sufficiently compensate the database administrator/IR assistant who will spend weeks if not months extracting, processing and merging the data from across campus for you to analyze. 
* Trust, but verify data quality. If something doesn't look right or match your records, ask. 
* Expect very long delays in getting data. This isn't a trivial process. 
* Request clear descriptions of data sources (real time vs snapshot)
  - It's hard to know what you want to analyze if you don't know what's collected.
* Student services data (EOP/Reach/DSS) seems to be very unstable or unreliable. These student programs tend to manage their own data records and are not consistently or cleanly attached to the more commonly used SIS data in a manner that lends itself well to analysis. 
* Don't be an overachiever. Most questions beget other questions. You cannot answer them all in one year!
    - Student success is a complicated issue that may never fully be understood. 






 