
# Abstract

*Background* Drug addiction prevalence continues to grow in this society, and negatively impacts individuals and the community in various ways including crime, medical and judicial costs, overdose, etc. A holistic approach to prevention and treatment of drug addiction is being recommended which includes nutrition professionals.  However, this population is not being covered by curriculum in nutrition courses at the college level. This pilot study examined the effect of a lesson delivered to college students in a nutrition course at California State University, Chico about individuals in drug addiction or recovery and if that altered their perceived confidence, knowledge and skills.

<hr>

*Methods* A curriculum was developed and implemented to these college students, along with a pre-post survey, that described individuals in drug addiction or recovery, their specific barriers, and how to help them overcome their barriers. There were 22 students that participated in this study. A Wilcoxon Signed Ranks test using SPSS was run to assess changes in mean pre to post scores for the three expected domains: perceived confidence, skills and knowledge. A Pearson’s Correlation was used to examine any relationship between age and change in pre to post survey scores. 


<hr>

<p>*Results* There was a significant increase in pre to post scores for perceived confidence (z = -2.005, p = .045), skills (z = -3.402, p = .001), and knowledge (z = -3.004, p = .003). There was no significance when comparing age and change in pre-post survey scores.
Conclusion This pilot study shows that providing college students with education on this population increases the students perceived confidence, skill level and knowledge. </p>



